title: Carlos Aguni Personal Blog
description: ~~Tales of an eternal apprentice~~
author: Carlos Aguni
github: https://github.com/crashlaker
about: Highly motivated self-taught IT analyst. Always learning and ready to explore new skills. An eternal apprentice.
google_analytics: 


owner:
  disqus-shortname: crashlaker

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    #- icon: fa-facebook
    #  link: "#"
    #- icon: fa-twitter
    #  link: "#"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/carlos-aguni"
    #- icon: fa-stack-exchange
    #  link: "#"
    - icon: fa-github
      link: "https://github.com/crashlaker"
    - icon: fa-medium
      link: "https://medium.com/@crashlaker"
    #- icon: "/assets/static/icons/observable.png"
    #  link: "https://observablehq.com/@crashlaker"

share:
  twitter_username: github.io
  fb_appid: 

urls:
    - text: About Me
      url: /about
    - text: My Projects
      url: /projects/
    - text: My Setup
      url: https://crashlaker.github.io/me/2020/09/02/my_setups.html
    - text: All Posts
      url: /posts
    - text: Tags
      url: /tags
    #- text: XML Feed
    #  url: /feed.xml

url: "https://crashlaker.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
#markdown: CommonMarkGhPages
markdown: kramdown
#kramdown:
#    parse_block_html: true

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html

kramdown:
  parse_block_html: true
#  syntax_highlighter_opts:
#    block:
#      line_numbers: true




gems:
  - jekyll-paginate
  - jekyll-gist

#compress_html:
#  clippings: all
#  comments: ["<!-- ", " -->"]
#  endings: all
#  ignore:
#    envs: ['development']
